# ---------------------------------------------------
# Server & Application Configuration
# 들여쓰기 중요함!!!!!
# spring: 은 최상단
# 나머지는 다 들여쓰기 되어있어야 오류 안납니다!!
# ---------------------------------------------------
spring:
  application:
    name: SchoolMATE

  server:
    port: 9000
    servlet:
      encoding:
        charset: UTF-8

  # ---------------------------------------------------
  # JWT (JSON Web Token) Configuration
  # ---------------------------------------------------
  jwt:
    secret: SahL5G83mGzrulJzffw-eD7RqphsXluJPBwxu0ncBFo
    expiration-time: "#{60 * 60 * 1000}" # 1시간임 실제 배포때는 시간 10분으로 바꿔야 함

  # ---------------------------------------------------
  # Spring Security OAuth2 Client Configuration
  # ---------------------------------------------------
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: f71b4c3a397902b27c666e262e974e86
            client-secret: qdDFsmPwuIHLopWVdmMe775FnewZnGZM
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # ---------------------------------------------------
  # Database (Datasource & JPA) Configuration
  # ---------------------------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kosa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

# ---------------------------------------------------
# Springdoc OpenAPI (Swagger) Configuration
# ---------------------------------------------------
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha

# ---------------------------------------------------
# Google Cloud Platform Configuration
# ---------------------------------------------------
google:
  cloud:
    credential:
      file:
        path: classpath:green-tract-4731b6-b3c9f9.json

# GCP Config
gcp:
  project-id: green-tract-473106-b3
