# ===================================================
# Server & Application Configuration
# ===================================================
server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: SchoolMATE

  # ===================================================
  # JWT (JSON Web Token) Configuration
  # ===================================================
  jwt:
    secret: SahL5G83mGzrulJzffw-eD7RqphsXluJPBwxu0ncBFo
    expiration-time: "#{60 * 60 * 1000}" # 1시간

  # ===================================================
  # Spring Security OAuth2 Client Configuration
  # ===================================================
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: f71b4c3a397902b27c666e262e974e86
            client-secret: qdDFsmPwuIHLopWVdmMe775FnewZnGZM
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # ===================================================
  # Database (Datasource & JPA) Configuration
  # ===================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kosa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

# ===================================================
# Springdoc OpenAPI (Swagger) Configuration
# ===================================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha

# ===================================================
# NEIS API Configuration
# ===================================================
neis:
  api-key: b79f732043e047e5adaa8b6f57a8dba8
  base-url: https://open.neis.go.kr/hub # 나이스 API 기본 URL
  path: # 각 서비스별 상세 경로
    school-info: /schoolInfo
    meal-service: /mealServiceDietInfo
    his-timetable: /hisTimetable
    mis-timetable: /misTimetable
    els-timetable: /elsTimetable
    school-schedule: /SchoolSchedule
    class-info: /classInfo
    school-major: /schoolMajorinfo

app:
  admin:
    email: admin@schoolmate.com
    password: 1234  # 초기화 로직에서 BCrypt로 인코딩될 평문 비밀번호

firebase:
  service-account-file: firebase/schoolmate-e3eef-firebase-adminsdk-fbsvc-6e850c88f7.json
  storage-bucket: "schoolmate-e3eef.firebasestorage.app"